Store/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Store.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace Store.Controllers
{
    [Authorize(Roles = "Admins")]
    public class AdminController : Controller
    {
        private IProductRepository repository;
        private IHostingEnvironment _environment;

        public AdminController(IProductRepository repo, IHostingEnvironment IHostingEnvironment)
        {
            repository = repo;
            _environment = IHostingEnvironment;
        }

        public ViewResult Index() => View(repository.Products);
        public ViewResult Edit(int productId) =>
View(repository.Products
.FirstOrDefault(p => p.ProductID == productId));

        [HttpPost]
        public IActionResult Edit(Product product, ICollection<IFormFile> image)
        {
            if (ModelState.IsValid)
            {
                var uploads = Path.Combine(_environment.WebRootPath, "images");
                foreach (var file in image)
                {
                    if (file.Length > 0)
                    {
                        using (var fileStream = new FileStream(Path.Combine(uploads, file.FileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                    }
                }
                repository.SaveProduct(product);
                TempData["message"] = $"{product.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(product);
            }
        }

        public ViewResult Create() => View("Edit", new Product());

        [HttpPost]
        public IActionResult Delete(int productId)
        {
            Product deletedProduct = repository.DeleteProduct(productId);
            if (deletedProduct != null)
            {
                TempData["message"] = $"{deletedProduct.Name} was deleted";
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult SeedDatabase()
        {
            SeedData.EnsurePopulated(HttpContext.RequestServices);
            return RedirectToAction(nameof(Index));
        }
    }
}

Store/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Store.Infrastructure;
using Store.Models;
using Store.Models.ViewModels;

namespace Store.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private Cart cart;
        public CartController(IProductRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            Product product = repository.Products
            .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToActionResult RemoveFromCart(int productId,
        string returnUrl)
        {
            Product product = repository.Products
            .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        [Authorize]
        public ViewResult Paypal(int productId, string returnUrl)
        {
            Product product = repository.Products
            .FirstOrDefault(p => p.ProductID == productId);
            string membership = product.Name;
            ViewBag.membership = membership;
            return View();
        }

    }
}

Store/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StackExchange.Redis;
using Store.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Store.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private Cart cart;
        private UserManager<AppUser> userManager;
        public OrderController(IOrderRepository repoService, Cart cartService, UserManager<AppUser> userMgr)
        {
            repository = repoService;
            cart = cartService;
            userManager = userMgr;
        }
        [Authorize]
        public ViewResult List() =>
View(repository.Orders.Where(o => !o.Shipped));
        [HttpPost]
        [Authorize]
        public IActionResult MarkShipped(int orderID)
        {
            Models.Order order = repository.Orders
            .FirstOrDefault(o => o.OrderID == orderID);
            if (order != null)
            {
                order.Shipped = true;
                repository.SaveOrder(order);
            }
            return RedirectToAction(nameof(List));
        }

        public ViewResult Checkout() => View(new Models.Order());
        [HttpPost]
        public IActionResult Checkout(Models.Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(order);
            }
        }
        private Task<AppUser> CurrentUser =>
        userManager.FindByNameAsync(HttpContext.User.Identity.Name);
        [HttpPost]
        public IActionResult MembershipCheckout(string membership)
        {
            Console.WriteLine("----------" + membership);
            MembershipTypes MembershipType;
            switch (membership)
            {

                case "Gold":
                    MembershipType = MembershipTypes.Gold;
                    break;
                case "Silver":
                    MembershipType = MembershipTypes.Silver;
                    break;
                case "Bronze":
                    MembershipType = MembershipTypes.Bronze;
                    break;
                default:
                    MembershipType = MembershipTypes.Gold;
                    break;
            }
            AppUser user = CurrentUser.Result;
            user.MembershipType = MembershipType;
            user.ExprireDate = DateTime.Now.AddMonths(12);
            userManager.UpdateAsync(user);
            Console.WriteLine("----------" + user.MembershipType);
            return RedirectToAction("List", "Product");

        }

        public ViewResult Completed()
        {
            cart.Clear();
            return View();
        }
    }
}

Store/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager


@if (User.IsInRole("Admins"))
{
    <a asp-controller="Admin" asp-action="index">Admin Panel</a>
}

@if (SignInManager.IsSignedIn(User))
{

    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a id="registerLink" asp-controller="Account" asp-action="Register" asp-route-returnurl="@ViewContext.HttpContext.Request.PathAndQuery()"> Register </a></li>
        <li><a id="loginLink" asp-controller="Account" asp-action="Login" asp-route-returnurl="@ViewContext.HttpContext.Request.PathAndQuery()"> Log in </a></li>
    </ul>
}

Store/Views/Shared/MembershipPartial.cshtml
@model ProductsListViewModel
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager
@if (!(ViewBag.Message == null))
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Message
    </div>
}
<h2 class="text-center">Check out Our Membership Deals:</h2>
<div class="row pr-5 pl-5">

    @foreach (var p in Model.Products)
    {
        @if (p.Category == "membership")
        {
            <div class="col-lg-4 col-md-6 mb-4 p-0 m-0">

                @Html.Partial("MembershipSummary", p)

            </div>

        }

    }
</div>

Store/Views/Shared/MembershipSummary.cshtml
@model Product
<div class="card h-100">
        <img class="card-img-top" src="~/images/@Model.Image" alt="Alternate Text" />
        <div class="card-body">
            <h4 class="card-title">
                @Model.Name
            </h4>
            <h5>@Model.Price.ToString("c")</h5>
        </div>
        <form id="@Model.ProductID" asp-action="Paypal"
              asp-controller="Cart" method="post">
            <input type="hidden" asp-for="ProductID" />
            <input type="hidden" name="returnUrl"
                   value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <button type="submit"
                    class="btn btn-success btn-sm pull-right" style="align-content:center; width:100%; ">
                Buy Now
            </button>
        </form>
</div>

Store/Views/Shared/ProductSummary.cshtml
@model Product
<div class="card h-100">
    <a href="#"><img class="card-img-top" src="~/images/@Model.Image" alt="Alternate Text" /></a>
    <div class="card-body">
        <h4 class="card-title">
            <a href="#">@Model.Name</a>
        </h4>
        <h5>@Model.Price.ToString("c")</h5>
        <p class="card-text">@Html.Raw(Model.Description)</p>
        
    </div>
    <form id="@Model.ProductID" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <button type="submit"
                    class="btn btn-success btn-sm pull-right" style="align-content:center; width:100%; background-color:lightgrey">
                Add To Cart
            </button>
    </form>
</div>

Store/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
</head>
<body class="m-2">
    <div class="bg-info p-2 row">
        <div class="col"><a class="navbar-brand btn btn-light" href="/">Drink Shop</a></div>

        <div class="col-4">
            <a class="btn btn-sm btn-primary"
               asp-action="Index" asp-controller="Admin">Products</a>
            <a class="btn btn-sm btn-primary"
               asp-action="List" asp-controller="Order">Orders</a>
            <a class="btn btn-sm btn-primary"
               asp-action="Index" asp-controller="User">Users</a>
            <a class="btn btn-sm btn-primary"
               asp-action="Index" asp-controller="RoleAdmin">Roles</a>
            <a class="btn btn-sm btn-primary"
               asp-action="Logout" asp-controller="Account">Log Out</a>
        </div>
    </div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success mt-1">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Drink Shop</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/dist/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />


</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/"><img src="~/images/white_logo.png" width="250" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav mr-auto pr-2">

                    
                    @await Component.InvokeAsync("NavigationMenu")
                    

                </ul>
                <ul class="navbar-nav ml-auto pl-2">
                    <li>@await Html.PartialAsync("LoginPartial")</li>
                    <li>@await Component.InvokeAsync("CartSummary")</li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        @if (this.ViewContext.RouteData.Values["controller"].ToString() == "Product")
    {
        @await Html.PartialAsync("MembershipPartial")
}
        
        @RenderBody()

    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

</body>

</html>